from typing import Protocol
from modules.identity_auth.domain.models import User


class AuthRepositoryPort(Protocol):
    def get_user_by_email(self, email: str) -> User | None: ...
    def get_password_hash_by_email(self, email: str) -> str | None: ...
    def create_user(self, email: str, password_hash: str) -> User: ...
    def get_user_by_id(self, user_id: str) -> User | None: ...